"""SQLAlchemy ORM models mirroring infra/db/migrations/002_schema.sql.

Option A (see plan / CLAUDE.md): the SQL migration is the source of truth for the
schema; these models give the app *typed* access for the ingestion write path (M5)
and Phase 2 retrieval. There is no Alembic autogeneration yet, so keep these models
in sync with the SQL by hand — a column added in one place must be added in the other.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    ForeignKey,
    Integer,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# Fixed dev-user id used until Supabase Auth lands. Because owner_id already exists
# and is NOT NULL, turning on per-user RLS later is a policy change, not a backfill.
DEV_OWNER_ID = uuid.UUID("00000000-0000-0000-0000-000000000000")


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""


class Document(Base):
    __tablename__ = "documents"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid() #not python generating the UUID but PostgreSQL db generates it as soon as the row is inserted
    )
    owner_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, default=DEV_OWNER_ID
    )
    filename: Mapped[str] = mapped_column(Text, nullable=False)
    content_type: Mapped[str | None] = mapped_column(Text)
    byte_size: Mapped[int | None] = mapped_column(Integer)
    checksum: Mapped[str | None] = mapped_column(Text)
    source_uri: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")
    error: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), onupdate=func.now()
    )

    chunks: Mapped[list[Chunk]] = relationship(
        back_populates="document",
        cascade="all, delete-orphan",
        passive_deletes=True,  # let the DB's ON DELETE CASCADE do the work
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('pending','processing','ready','failed')",
            name="documents_status_check",
        ),
    )


class Chunk(Base):
    __tablename__ = "chunks"

    # bigint IDENTITY, generated by the DB — the app never supplies it on insert.
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    owner_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, default=DEV_OWNER_ID
    )
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[list[float]] = mapped_column(Vector(768), nullable=False)
    char_count: Mapped[int] = mapped_column(Integer, nullable=False)
    token_count: Mapped[int | None] = mapped_column(Integer)
    element_type: Mapped[str | None] = mapped_column(Text)
    section_title: Mapped[str | None] = mapped_column(Text)
    page_number: Mapped[int | None] = mapped_column(Integer)
    # `metadata` is reserved on Declarative Base, so the python attr is `metadata_`
    # while the DB column stays `metadata`.
    metadata_: Mapped[dict] = mapped_column(
        "metadata", JSONB, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())

    document: Mapped[Document] = relationship(back_populates="chunks")

    __table_args__ = (
        UniqueConstraint(
            "document_id", "ordinal", name="chunks_document_id_ordinal_key"
        ),
    )
